@echo off
cd /d c:\Users\Seito\Github\roam
start "whiskey" cmd /c "node scripts/seed-whiskey.mjs && pause"
start "watches" cmd /c "node scripts/seed-watches.mjs && pause"
start "craft-beer" cmd /c "node scripts/seed-craft-beer.mjs && pause"
start "audio-hifi" cmd /c "node scripts/seed-audio-hifi.mjs && pause"
start "motorcycles" cmd /c "node scripts/seed-motorcycles.mjs && pause"
start "mma" cmd /c "node scripts/seed-mma.mjs && pause"
start "military-history" cmd /c "node scripts/seed-military-history.mjs && pause"
start "aviation" cmd /c "node scripts/seed-aviation.mjs && pause"
start "woodworking" cmd /c "node scripts/seed-woodworking.mjs && pause"
start "bbq" cmd /c "node scripts/seed-bbq.mjs && pause"
start "survival" cmd /c "node scripts/seed-survival.mjs && pause"
start "natgeo" cmd /c "node scripts/seed-natgeo.mjs && pause"
start "iflscience" cmd /c "node scripts/seed-iflscience.mjs && pause"
start "seriouseats" cmd /c "node scripts/seed-seriouseats.mjs && pause"
start "outside" cmd /c "node scripts/seed-outside.mjs && pause"
start "kotaku" cmd /c "node scripts/seed-kotaku.mjs && pause"
start "lonelyplanet" cmd /c "node scripts/seed-lonelyplanet.mjs && pause"
start "roadtrippers" cmd /c "node scripts/seed-roadtrippers.mjs && pause"
start "archdaily" cmd /c "node scripts/seed-archdaily.mjs && pause"
start "bringatrailer" cmd /c "node scripts/seed-bringatrailer.mjs && pause"