@echo off
cd /d c:\Users\Seito\Github\roam
start "whiskey" cmd /c "node scripts/seed-whiskey.mjs && pause"
start "watches" cmd /c "node scripts/seed-watches.mjs && pause"
start "craft-beer" cmd /c "node scripts/seed-craft-beer.mjs && pause"
start "audio-hifi" cmd /c "node scripts/seed-audio-hifi.mjs && pause"
start "motorcycles" cmd /c "node scripts/seed-motorcycles.mjs && pause"
start "mma" cmd /c "node scripts/seed-mma.mjs && pause"
start "military-history" cmd /c "node scripts/seed-military-history.mjs && pause"
start "aviation" cmd /c "node scripts/seed-aviation.mjs && pause"
start "woodworking" cmd /c "node scripts/seed-woodworking.mjs && pause"
start "strength-fitness" cmd /c "node scripts/seed-strength-fitness.mjs && pause"
start "sneakers" cmd /c "node scripts/seed-sneakers.mjs && pause"
start "survival" cmd /c "node scripts/seed-survival.mjs && pause"
start "snow-sports" cmd /c "node scripts/seed-snow-sports.mjs && pause"
start "mens-grooming" cmd /c "node scripts/seed-mens-grooming.mjs && pause"
start "bbq" cmd /c "node scripts/seed-bbq.mjs && pause"
REM ── New PETS seeders ────────────────────────────
start "cattledog" cmd /c "node scripts/seed-cattledog.mjs && pause"
start "insightfulanimals" cmd /c "node scripts/seed-insightfulanimals.mjs && pause"
start "aspca" cmd /c "node scripts/seed-aspca.mjs && pause"
start "akc" cmd /c "node scripts/seed-akc.mjs && pause"
REM ── New FISHING seeders ──────────────────────────
start "simpson-fly-fishing" cmd /c "node scripts/seed-simpson-fly-fishing.mjs && pause"
start "flyfisherman" cmd /c "node scripts/seed-flyfisherman.mjs && pause"
start "coastal-angler" cmd /c "node scripts/seed-coastal-angler.mjs && pause"
start "saltwater-sportsman" cmd /c "node scripts/seed-saltwater-sportsman.mjs && pause"
start "on-the-water" cmd /c "node scripts/seed-on-the-water.mjs && pause"
start "in-fisherman" cmd /c "node scripts/seed-in-fisherman.mjs && pause"
start "wired2fish" cmd /c "node scripts/seed-wired2fish.mjs && pause"
start "field-and-stream" cmd /c "node scripts/seed-field-and-stream.mjs && pause"
REM ── New COOKING seeders ──────────────────────────
start "forks-over-knives" cmd /c "node scripts/seed-forks-over-knives.mjs && pause"
start "food52" cmd /c "node scripts/seed-food52.mjs && pause"