// tests/check-rules.test.ts
//
// Vitest unit tests for scripts/check-rules.mjs.
// Verifies the rule engine catches the known footguns from RUNBOOK.md and
// honors the allowlist.
//
// Run: cd extension && pnpm vitest run src/__tests__/check-rules.test.ts

import { describe, it, expect, beforeAll, beforeEach, afterEach, afterAll } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const SCRIPT_PATH = join(__dirname, '..', '..', '..', 'scripts', 'check-rules.mjs');

interface ScriptResult {
  status: number;
  stdout: string;
  stderr: string;
}

function runScript(cwd: string): ScriptResult {
  const result = spawnSync('node', [SCRIPT_PATH], {
    cwd,
    encoding: 'utf8',
    maxBuffer: 50 * 1024 * 1024,
  });
  return {
    status: result.status ?? -1,
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
  };
}

describe('check-rules.mjs', () => {
  let workDir: string;
  let originalCwd: string;

  beforeAll(() => {
    originalCwd = process.cwd();
  });

  beforeEach(() => {
    // Each test gets a fresh tmpdir so files don't bleed between tests.
    workDir = mkdtempSync(join(tmpdir(), 'roam-rules-test-'));
  });

  afterEach(() => {
    if (workDir) {
      try { rmSync(workDir, { recursive: true, force: true }); } catch {}
      workDir = '';
    }
  });

  afterAll(() => {
    process.chdir(originalCwd);
  });

  it('passes a clean directory', () => {
    process.chdir(workDir);
    const result = runScript(workDir);
    // The rules script returns 0 if no errors (warnings are OK).
    expect(result.status).toBe(0);
  });

  it('fails on a hardcoded secret prefix', () => {
    process.chdir(workDir);
    writeFileSync(join(workDir, 'leaked.ts'), `const key = "sntryu_abc123def456ghi789jkl012mno";\n`);
    const result = runScript(workDir);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/R3/);
  });

  it('fails on an attribution of automated authorship', () => {
    process.chdir(workDir);
    writeFileSync(join(workDir, 'code.ts'), `// Generated by an LLM.\nconst x = 1;\n`);
    const result = runScript(workDir);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/R2/);
  });

  it('fails on `as any`', () => {
    process.chdir(workDir);
    writeFileSync(join(workDir, 'cast.ts'), `const x = something as any;\n`);
    const result = runScript(workDir);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/R9/);
  });

  it('honors the allowlist file', () => {
    process.chdir(workDir);
    writeFileSync(join(workDir, 'allowed.ts'), `const x = something as any;\n`);
    // mkdirSync must run before writeFileSync for the scripts/ directory.
    mkdirSync(join(workDir, 'scripts'), { recursive: true });
    writeFileSync(join(workDir, 'scripts', '.agent-rules-allowlist'), `R9: allowed.ts\n`);
    const result = runScript(workDir);
    expect(result.status).toBe(0);
  });

  it('fails on .skip migration in active directory', () => {
    process.chdir(workDir);
    mkdirSync(join(workDir, 'supabase', 'migrations'), { recursive: true });
    writeFileSync(join(workDir, 'supabase', 'migrations', '20260101000000_test.sql.skip'), '-- skipped\n');
    const result = runScript(workDir);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/R4/);
  });

  it('fails on duplicate component filenames', () => {
    process.chdir(workDir);
    mkdirSync(join(workDir, 'web', 'src', 'components'), { recursive: true });
    mkdirSync(join(workDir, 'web', 'src', 'app', 'foo'), { recursive: true });
    writeFileSync(join(workDir, 'web', 'src', 'components', 'Both.tsx'), 'export const x = 1;\n');
    writeFileSync(join(workDir, 'web', 'src', 'app', 'foo', 'Both.tsx'), 'export const x = 2;\n');
    const result = runScript(workDir);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/R5/);
  });

  it('fails on proxy.ts presence', () => {
    process.chdir(workDir);
    mkdirSync(join(workDir, 'web', 'src'), { recursive: true });
    writeFileSync(join(workDir, 'web', 'src', 'proxy.ts'), 'export async function proxy() {}\n');
    const result = runScript(workDir);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/R6/);
  });
});