package app.roam.android.util

import android.content.Context
import android.media.AudioManager
import android.media.SoundPool
import app.roam.android.R

/**
 * Low-latency sound-effect player built on [SoundPool].
 *
 * Respects two layers of gating:
 * 1. The device ringer mode (silent / vibrate) — checked here so sounds never
 *    play while the phone is muted, regardless of the in-app toggle.
 * 2. The in-app "Sound effects" toggle — checked by the caller (MainViewModel)
 *    before calling [play].
 *
 * The WAV assets in `res/raw/` are short, royalty-free clips generated by
 * `scripts/generate-sfx.mjs` (original synthesized tones — no attribution required).
 */
object SoundManager {
    private var soundPool: SoundPool? = null
    private val soundIds = mutableMapOf<Int, Int>()

    /** Loads all SFX once. Safe to call repeatedly — subsequent calls are no-ops. */
    fun init(context: Context) {
        if (soundPool != null) return
        val appContext = context.applicationContext
        val attributes = android.media.AudioAttributes.Builder()
            .setUsage(android.media.AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
            .setContentType(android.media.AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .build()
        soundPool = SoundPool.Builder()
            .setMaxStreams(4)
            .setAudioAttributes(attributes)
            .build()
            .also { pool ->
                listOf(
                    R.raw.badge_earn,
                    R.raw.level_up,
                    R.raw.challenge_complete,
                    R.raw.generic_success,
                ).forEach { resId -> soundIds[resId] = pool.load(appContext, resId, 1) }
            }
    }

    /** Plays [resId] if the device is not silenced/vibrating. */
    fun play(context: Context, resId: Int) {
        val audioManager = context.getSystemService(Context.AUDIO_SERVICE) as? AudioManager ?: return
        val ringerMode = audioManager.ringerMode
        if (ringerMode == AudioManager.RINGER_MODE_SILENT || ringerMode == AudioManager.RINGER_MODE_VIBRATE) {
            return
        }
        val pool = soundPool ?: return
        val id = soundIds[resId] ?: return
        pool.play(id, 1f, 1f, 1, 0, 1f)
    }
}
