#!/usr/bin/env node
// check-rules.mjs
//
// Local + CI enforcement of the project rules.
// Run from the repo root:
//   node scripts/check-rules.mjs
//
// Exit codes:
//   0 = no rule violations (warnings are OK)
//   1 = at least one rule violation
//
// Each rule has a stable ID (R1, R2, ...). To allow a check on a specific file,
// add an entry to scripts/.rules-allowlist:
//
//   R9: extension/src/legacy.ts
//
// Supported glob patterns:
//   - exact path:        web/src/lib/foo.ts
//   - dir + /** suffix:  scripts/legacy/**

import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, relative, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const ALLOWLIST_PATH = 'scripts/.rules-allowlist';

const EXT_TS = ['.ts', '.tsx', '.mts', '.cts'];
const EXT_SQL = ['.sql'];
const EXT_DOCS = ['.md', '.txt'];
const ALL_SOURCE_EXTS = [...EXT_TS, ...EXT_SQL, '.kt', '.mjs', '.js', ...EXT_DOCS];

const BUILD_OUTPUT_DIRS = new Set([
  'dist', 'dist-firefox', 'build', '.next', '_superseded', 'coverage',
  'node_modules', '.git', '.gradle', '.kotlin', '.idea', '.cache',
]);

const SECRET_PREFIXES = [
  'AIza', 'sk-', 'sntryu_', 'sbp_', 'sb_secret_',
  'sb_publishable_', 're_', 'KGAT_',
];

const ATTRIBUTION_PATTERNS = [
  /\bAI[\s-]?generated\b/i,
  /\bAI[\s-]?assisted\b/i,
  /\bgenerated by (an? )?(LLM|model|AI|Claude|GPT|Copilot|Cursor|Continue|Aider)\b/i,
  /\bprompted by\b/i,
  /\bthe (model|agent|LLM|AI)\b/i,
  /\bCLAUDE\.md\b/,
  /\bcopilot[\s-]?instructions\b/i,
  /\bClaude Code\b/,
  /\bChatGPT\b/,
];

// Note: the rulebook filename is intentionally not in this list. The
// rulebook lives at RULES.md and is part of RULES_FILES below.

const RULES_FILES = new Set([
  'RULES.md', 'web/RULES.md', 'extension/RULES.md',
  'supabase/RULES.md', 'android/RULES.md',
  'CONTRIBUTING.md', 'RUNBOOK.md', '.github/pull_request_template.md',
  'scripts/check-rules.mjs', 'scripts/.rules-allowlist',
  '.env.example', 'web/.env.example', 'extension/.env.example',
  'android/.env.example', 'docs/CONTEXT.md',
  // Public-facing contributor docs. They explicitly reference the rulebook
  // by name in places; the wording is hand-curated to comply with R2.
  'README.md', 'CODE_OF_CONDUCT.md', 'SECURITY.md', 'LICENSE',
]);

let violations = 0;
let warnings = 0;
const errors = [];
const warningsList = [];

function fail(ruleId, file, line, message) {
  violations++;
  errors.push(`  [${ruleId}] ${file}${line ? ':' + line : ''} - ${message}`);
}

function warn(ruleId, file, line, message) {
  warnings++;
  warningsList.push(`  [${ruleId}] ${file}${line ? ':' + line : ''} - ${message}`);
}

const SCRIPT_DIR = fileURLToPath(new URL('.', import.meta.url)).replace(/[\\/]+$/, '');
const CWD = process.cwd();
const ROOT = (CWD.endsWith(`${'\\'}scripts`) || CWD.endsWith('/scripts'))
  ? SCRIPT_DIR.replace(/[\\/]scripts$/, '')
  : CWD;
process.chdir(ROOT);

function loadAllowlist() {
  if (!existsSync(ALLOWLIST_PATH)) return new Map();
  const map = new Map();
  for (const raw of readFileSync(ALLOWLIST_PATH, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf(':');
    if (idx < 0) continue;
    const ruleId = line.slice(0, idx).trim();
    const glob = line.slice(idx + 1).trim();
    if (!map.has(ruleId)) map.set(ruleId, []);
    map.get(ruleId).push(glob);
  }
  return map;
}

const ALLOWLIST = loadAllowlist();

function isAllowed(ruleId, file) {
  const entries = ALLOWLIST.get(ruleId);
  if (!entries) return false;
  const rel = file.replace(/\\/g, '/');
  return entries.some(pattern => {
    if (pattern === rel) return true;
    if (pattern.endsWith('/**')) {
      const prefix = pattern.slice(0, -3);
      return rel.startsWith(prefix + '/') || rel === prefix;
    }
    if (pattern.startsWith('**/')) return rel.endsWith(pattern.slice(3));
    return false;
  });
}

function walk(dir, files = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (BUILD_OUTPUT_DIRS.has(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else files.push(full);
  }
  return files;
}

const allFiles = walk(process.cwd());
const sourceFiles = allFiles.filter(f => ALL_SOURCE_EXTS.includes(extname(f)));
// Workflow files are scanned by R10 even though they aren't "source files".
const workflowFiles = allFiles.filter(f =>
  (f.endsWith('.yml') || f.endsWith('.yaml')) &&
  f.replace(/\\/g, '/').includes('.github/workflows/')
);

// ─── R1: No `[deploy]` in commit messages ──────────────────────────────────
// Matches the historical pattern used by the (now-removed) GitHub Actions
// trigger: a tag like "[deploy]" appended at the END of the subject line.
// Subject-internal "[deploy]" mentions (e.g., an explanatory commit body
// or a commit about removing the trigger) do not trip the rule.
function checkDeployTagInCommits() {
  let out = '';
  try {
    out = execSync('git log --pretty=%s origin/main..HEAD', { encoding: 'utf8' });
  } catch {
    return;
  }
  const tags = ['[deploy]', '[ship]', '[prod]', '[release]'];
  // Match: optional whitespace, the tag, optional trailing whitespace, end of line.
  const trailingTagRe = /\s*\[(deploy|ship|prod|release)\]\s*$/i;
  for (const line of out.split(/\r?\n/)) {
    if (trailingTagRe.test(line)) {
      const m = line.match(trailingTagRe);
      fail('R1', 'git log', null,
        `commit-message trigger tag "[${m[1]}]" found at end of subject - see Hard Rule 1.1`);
      return; // one violation is enough
    }
  }
}
checkDeployTagInCommits();

// ─── R2: No attribution of automated authorship ────────────────────────────
// The `docs/archive/` and `supabase/migrations/_superseded/` directories
// contain historical snapshots that legitimately reference the tooling
// that authored them (or context that was used at the time). Those docs
// are stripped from the public mirror by `sync-public.ps1`, so scanning
// them here would surface false positives without protecting the public.
function checkAttribution(file) {
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  if (RULES_FILES.has(rel)) return;
  if (rel.startsWith('supabase/migrations/_superseded/')) return;
  if (rel.startsWith('docs/archive/')) return;
  let content;
  try { content = readFileSync(file, "utf8"); } catch { /* file unreadable - skip */ return; }
  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    for (const pattern of ATTRIBUTION_PATTERNS) {
      if (pattern.test(line)) {
        if (isAllowed('R2', rel)) return;
        fail('R2', rel, i + 1,
          `attribution of automated authorship "${line.trim().slice(0, 80)}" - see Hard Rule 1.2`);
        return;
      }
    }
  }
}

// ─── R3: No hardcoded secrets ──────────────────────────────────────────────
function checkSecrets(file) {
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  if (rel.endsWith('.env') || rel.endsWith('.env.example') || rel.endsWith('.env.local')) return;
  if (rel.includes('.example')) return;
  if (rel.startsWith('web/coverage/') || rel.startsWith('web/.next/')) return;
  let content;
  try { content = readFileSync(file, "utf8"); } catch { /* file unreadable - skip */ return; }
  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*(--|\/\/|#|<!--)/.test(line)) continue;
    for (const prefix of SECRET_PREFIXES) {
      const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`\\b${escaped}[A-Za-z0-9_\\-]{16,}\\b`);
      if (re.test(line)) {
        if (isAllowed('R3', rel)) return;
        fail('R3', rel, i + 1,
          `hardcoded secret prefix "${prefix}" - see Hard Rule 1.3`);
        return;
      }
    }
  }
}

// ─── R4: No .skip migrations in active directory ───────────────────────────
function checkSkipMigrations() {
  const dir = 'supabase/migrations';
  if (!existsSync(dir)) return;
  for (const f of readdirSync(dir)) {
    if (f.endsWith('.skip')) {
      fail('R4', `${dir}/${f}`, null,
        '.skip migration in active directory - move to _superseded/ per Hard Rule 1.4');
    }
  }
}
checkSkipMigrations();

// ─── R5: No duplicate component filenames ─────────────────────────────────
function checkDuplicateComponents() {
  const componentsDir = 'web/src/components';
  const appDir = 'web/src/app';
  if (!existsSync(componentsDir) || !existsSync(appDir)) return;
  const componentFiles = new Set(
    readdirSync(componentsDir, { recursive: true })
      .filter(f => extname(f) === '.tsx' || extname(f) === '.ts')
      .map(f => basename(f))
  );
  function walkApp(dir) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walkApp(join(dir, entry.name));
      else if ((extname(entry.name) === '.tsx' || extname(entry.name) === '.ts') &&
               componentFiles.has(entry.name)) {
        fail('R5', `${relative(ROOT, join(dir, entry.name))}`, null,
          `filename matches web/src/components/${entry.name} - duplicate-component pattern, see Hard Rule 1.7`);
      }
    }
  }
  walkApp(appDir);
}
checkDuplicateComponents();

// ─── R6: No proxy.ts in web/src/ ───────────────────────────────────────────
function checkProxyTs() {
  const candidate = 'web/src/proxy.ts';
  if (existsSync(candidate)) {
    fail('R6', candidate, null,
      'proxy.ts exists - should be middleware.ts, see Hard Rule 1.8');
  }
}
checkProxyTs();


// ─── R7: SQL migration safety (array_agg(u.*) pattern from v31) ───────────
function checkSqlPatterns(file) {
  if (!file.endsWith('.sql')) return;
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  if (rel.includes('_superseded')) return;
  let content;
  try { content = readFileSync(file, "utf8"); } catch { /* file unreadable - skip */ return; }
  if (/array_agg\s*\(\s*u\./i.test(content)) {
    if (isAllowed('R7', rel)) return;
    warn('R7', rel, null,
      'migration uses "array_agg(u.*)" - verify the alias scope, see Backend Rule S.7');
  }
}

// ─── R8: No empty catch {} without comment ─────────────────────────────────
function checkEmptyCatches(file) {
  if (![...EXT_TS, '.js', '.mjs'].some(ext => file.endsWith(ext))) return;
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  if (rel.startsWith('node_modules/') || rel.includes('/coverage/')) return;
  let content;
  try { content = readFileSync(file, 'utf8'); } catch { /* file unreadable - skip */ return; }
  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Skip comment-only lines and strings. Use a regex that requires the
    // catch to be at code position (not inside a `// ...` comment or string).
    if (/^\s*(\/\/|\*|<!--)/.test(line)) continue;
    // Strip line comments before testing; catches inside comments are OK.
    const code = line.replace(/\/\/.*$/, '');
    if (/catch\s*(\([^)]*\))?\s*\{\s*\}/.test(code)) {
      if (isAllowed('R8', rel)) continue;
      fail('R8', rel, i + 1, 'empty catch without comment - see Process Rule 2.5');
    }
  }
}

// ─── R9: No `as any` casts ────────────────────────────────────────────────
function checkAnyCast(file) {
  if (!EXT_TS.includes(extname(file))) return;
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  if (rel.startsWith('node_modules/') || rel.includes('/coverage/')) return;
  let content;
  try { content = readFileSync(file, "utf8"); } catch { /* file unreadable - skip */ return; }
  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/\bas\s+any\b/.test(line)) {
      if (isAllowed('R9', rel)) continue;
      fail('R9', rel, i + 1,
        '"as any" cast - use "as unknown as T" with comment, see Process Rule 2.6');
    }
  }
}

// ─── R10: No `contains(fromJSON([...]))` predicates in workflow files ──────
// GitHub Actions' `contains()` helper does element matching on arrays, not
// glob matching. Wrapping it in `fromJSON(['supabase/functions/**'])` and
// then comparing to '**' or '*' is always false (or always true), silently
// breaking the workflow. See RULES.md §1.6½.
function checkWorkflowPathFilter(file) {
  if (!file.endsWith('.yml') && !file.endsWith('.yaml')) return;
  const rel = relative(ROOT, file).replace(/\\/g, '/');
  if (!rel.startsWith('.github/workflows/')) return;
  let content;
  try { content = readFileSync(file, "utf8"); } catch { /* file unreadable - skip */ return; }
  const lines = content.split(/\r?\n/);
  // Match an `if:` (or `steps[].if`) line that contains the antipattern.
  // We catch both the array-with-'**' form (always false) and the array-with-'*'
  // form (always true). Both hide bugs.
  const re = /contains\s*\(\s*fromJSON\s*\(/i;
  let insideIf = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*if\s*:/.test(line) || /\bif\s*:/.test(line)) insideIf = true;
    if (insideIf && re.test(line)) {
      if (isAllowed('R10', rel)) continue;
      fail('R10', rel, i + 1,
        'contains(fromJSON([...])) is always true or false in an `if:` predicate — use dorny/paths-filter instead. See RULES.md §1.6½');
    }
    if (line.trim() === '' || /^[^\s]/.test(line)) insideIf = false;
  }
}

// ─── Run all per-file checks ──────────────────────────────────────────────
console.log(`Scanning ${sourceFiles.length} source files...`);

for (const file of sourceFiles) {
  checkAttribution(file);
  checkSecrets(file);
  checkSqlPatterns(file);
  checkEmptyCatches(file);
  checkAnyCast(file);
}

for (const file of workflowFiles) {
  checkWorkflowPathFilter(file);
}

// ─── Report ────────────────────────────────────────────────────────────────
if (errors.length === 0 && warningsList.length === 0) {
  console.log('OK: All rules pass.');
  process.exit(0);
}

if (warningsList.length > 0) {
  console.warn(`\nWARNING: ${warnings} warning(s):\n`);
  for (const w of warningsList) console.warn(w);
}

if (errors.length === 0) {
  console.log('OK: No rule violations. Warnings above are informational.');
  process.exit(0);
}

console.error(`\nFAIL: ${violations} rule violation(s):\n`);
for (const err of errors) console.error(err);
console.error(`\nSee RULES.md for the rule each ID refers to.`);
console.error(`To allow a specific violation, add an entry to ${ALLOWLIST_PATH}`);
console.error(`in the format "<RULE_ID>: <glob-pattern>".`);
process.exit(1);
