-- Seed the canonical tag vocabulary (see scripts/lib/tag-vocabulary.mjs).
-- GENERATED FILE — do not edit by hand. Run: node scripts/generate-tag-artifacts.mjs

INSERT INTO public.tags (slug, display_name, pillar, description) VALUES
  ('artificial-intelligence', 'Artificial Intelligence', 'science-nature', 'AI, ML, neural networks, LLMs, machine learning applications'),
  ('machine-learning', 'Machine Learning', 'science-nature', 'ML algorithms, training, inference, model development'),
  ('deep-learning', 'Deep Learning', 'science-nature', 'Neural networks, transformers, deep architectures'),
  ('nlp', 'NLP', 'science-nature', 'Natural language processing, text analysis, language models'),
  ('computer-vision', 'Computer Vision', 'science-nature', 'Image recognition, object detection, visual AI'),
  ('robotics', 'Robotics', 'science-nature', 'Robots, automation, autonomous systems'),
  ('ai-safety', 'AI Safety', 'science-nature', 'AI alignment, safety research, existential risk'),
  ('data-science', 'Data Science', 'science-nature', 'Data analysis, statistics, visualization'),
  ('data-engineering', 'Data Engineering', 'science-nature', 'Data pipelines, ETL, data infrastructure'),
  ('space-astronomy', 'Space & Astronomy', 'science-nature', 'Stars, galaxies, cosmology, telescopes, celestial objects'),
  ('astrobiology', 'Astrobiology', 'science-nature', 'Life in the universe, exoplanets, origin of life'),
  ('space-exploration', 'Space Exploration', 'science-nature', 'NASA, SpaceX, rockets, missions, astronauts'),
  ('physics', 'Physics', 'science-nature', 'Quantum mechanics, relativity, particle physics'),
  ('chemistry', 'Chemistry', 'science-nature', 'Chemical reactions, materials, molecular science'),
  ('biology', 'Biology', 'science-nature', 'Life sciences, organisms, ecosystems'),
  ('genetics', 'Genetics', 'science-nature', 'DNA, genes, heredity, CRISPR, genomics'),
  ('evolution', 'Evolution', 'science-nature', 'Evolutionary biology, natural selection, speciation'),
  ('neuroscience', 'Neuroscience', 'science-nature', 'Brain science, neurons, cognition, consciousness'),
  ('ecology', 'Ecology', 'science-nature', 'Ecosystems, biodiversity, environmental interactions'),
  ('conservation', 'Conservation', 'science-nature', 'Wildlife protection, habitat preservation, endangered species'),
  ('climate-science', 'Climate Science', 'science-nature', 'Climate change, global warming, atmospheric science'),
  ('environmental-sustainability', 'Environmental Sustainability', 'science-nature', 'Green energy, sustainable living, circular economy'),
  ('geology', 'Geology', 'science-nature', 'Rocks, minerals, Earth structure, plate tectonics'),
  ('oceanography', 'Oceanography', 'science-nature', 'Oceans, marine science, currents, sea life'),
  ('paleontology', 'Paleontology', 'science-nature', 'Fossils, dinosaurs, prehistoric life'),
  ('medicine', 'Medicine', 'science-nature', 'Medical research, treatments, healthcare science'),
  ('epidemiology', 'Epidemiology', 'science-nature', 'Disease spread, public health, pandemics'),
  ('immunology', 'Immunology', 'science-nature', 'Immune system, antibodies, vaccines, autoimmunity'),
  ('microbiology', 'Microbiology', 'science-nature', 'Bacteria, microbes, microbiome, single-celled life'),
  ('virology', 'Virology', 'science-nature', 'Viruses, viral diseases, vaccine research'),
  ('mathematics', 'Mathematics', 'science-nature', 'Pure math, applied math, statistics, proofs'),
  ('zoology', 'Zoology', 'science-nature', 'Animal biology, behavior, species'),
  ('botany', 'Botany', 'science-nature', 'Plant science, flora, vegetation'),
  ('mycology', 'Mycology', 'science-nature', 'Fungi, mushrooms, lichens'),
  ('entomology', 'Entomology', 'science-nature', 'Insects, arachnids, arthropod study'),
  ('marine-biology', 'Marine Biology', 'science-nature', 'Ocean life, marine ecosystems, sea creatures'),
  ('meteorology', 'Meteorology', 'science-nature', 'Weather, climate systems, atmospheric phenomena'),
  ('materials-science', 'Materials Science', 'science-nature', 'New materials, nanotechnology, composites'),
  ('science-communication', 'Science Communication', 'science-nature', 'Explaining science, science writing, public understanding'),
  ('programming', 'Programming', 'technology', 'Coding, software development, programming languages'),
  ('web-development', 'Web Development', 'technology', 'Websites, web apps, HTML, CSS, JavaScript'),
  ('backend', 'Backend', 'technology', 'Server-side development, APIs, databases'),
  ('frontend', 'Frontend', 'technology', 'UI development, React, Vue, browser technologies'),
  ('devops', 'DevOps', 'technology', 'CI/CD, infrastructure, deployment, monitoring'),
  ('databases', 'Databases', 'technology', 'SQL, NoSQL, data storage, query optimization'),
  ('cybersecurity', 'Cybersecurity', 'technology', 'Security, hacking, encryption, vulnerabilities'),
  ('privacy', 'Privacy', 'technology', 'Data privacy, surveillance, digital rights'),
  ('blockchain', 'Blockchain', 'technology', 'Distributed ledgers, smart contracts, DeFi'),
  ('cryptocurrency', 'Cryptocurrency', 'technology', 'Bitcoin, Ethereum, digital currencies'),
  ('hardware', 'Hardware', 'technology', 'Computer hardware, chips, processors, devices'),
  ('mobile-development', 'Mobile Development', 'technology', 'iOS, Android, mobile app development'),
  ('cloud-computing', 'Cloud Computing', 'technology', 'AWS, Azure, GCP, cloud infrastructure'),
  ('open-source', 'Open Source', 'technology', 'OSS projects, community, licensing'),
  ('developer-tools', 'Developer Tools', 'technology', 'IDEs, version control, productivity tools'),
  ('internet-culture', 'Internet Culture', 'technology', 'Memes, online communities, digital trends'),
  ('vintage-computing', 'Vintage Computing', 'technology', 'Retro computers, old software, computing history'),
  ('emerging-technology', 'Emerging Technology', 'technology', 'Future tech, cutting-edge innovations'),
  ('startups', 'Startups', 'technology', 'Startup culture, venture capital, entrepreneurship'),
  ('marketing', 'Marketing', 'technology', 'Digital marketing, growth, advertising'),
  ('social-media', 'Social Media', 'technology', 'Social platforms, online communities, trends'),
  ('fintech', 'Fintech', 'technology', 'Financial technology, payments, banking innovation'),
  ('esports', 'Esports', 'technology', 'Competitive gaming, tournaments, pro players'),
  ('quantum-computing', 'Quantum Computing', 'technology', 'Quantum computers, qubits, quantum algorithms'),
  ('iot', 'IoT', 'technology', 'Internet of things, smart homes, connected devices'),
  ('vr-ar', 'VR & AR', 'technology', 'Virtual reality, augmented reality, spatial computing'),
  ('accessibility', 'Accessibility', 'technology', 'Digital accessibility, assistive technology, a11y'),
  ('visual-art', 'Visual Art', 'arts-culture', 'Painting, sculpture, contemporary art'),
  ('photography', 'Photography', 'arts-culture', 'Photo techniques, photographers, photo essays'),
  ('film', 'Film', 'arts-culture', 'Movies, cinema, filmmaking, directors, film history'),
  ('television', 'Television', 'arts-culture', 'TV shows, series, broadcasting'),
  ('animation', 'Animation', 'arts-culture', 'Animated films, cartoons, motion graphics'),
  ('anime', 'Anime', 'arts-culture', 'Japanese animation, manga adaptations'),
  ('manga', 'Manga', 'arts-culture', 'Japanese comics, graphic novels'),
  ('comics', 'Comics', 'arts-culture', 'Comic books, graphic novels, webcomics'),
  ('music', 'Music', 'arts-culture', 'Musical genres, artists, music theory'),
  ('literature', 'Literature', 'arts-culture', 'Books, novels, poetry, literary criticism'),
  ('poetry', 'Poetry', 'arts-culture', 'Poems, poets, verse'),
  ('theater', 'Theater', 'arts-culture', 'Plays, stage performance, drama'),
  ('dance', 'Dance', 'arts-culture', 'Dance styles, choreography, performance'),
  ('architecture', 'Architecture', 'arts-culture', 'Buildings, design, urban planning'),
  ('design', 'Design', 'arts-culture', 'Graphic design, UX, product design'),
  ('industrial-design', 'Industrial Design', 'arts-culture', 'Product design, manufacturing design'),
  ('fashion', 'Fashion', 'arts-culture', 'Clothing, style, fashion industry'),
  ('street-art', 'Street Art', 'arts-culture', 'Graffiti, murals, urban art'),
  ('digital-art', 'Digital Art', 'arts-culture', 'Digital illustration, generative art, NFTs'),
  ('art-history', 'Art History', 'arts-culture', 'Art movements, art historical periods, criticism'),
  ('classical-music', 'Classical Music', 'arts-culture', 'Orchestral, chamber, opera, classical composers'),
  ('jazz', 'Jazz', 'arts-culture', 'Jazz, blues, improvisation, standards'),
  ('electronic-music', 'Electronic Music', 'arts-culture', 'EDM, techno, ambient, electronic production'),
  ('hip-hop', 'Hip-Hop', 'arts-culture', 'Rap, hip-hop culture, beats, MCing'),
  ('rock-music', 'Rock Music', 'arts-culture', 'Rock, metal, punk, guitar-driven music'),
  ('folk-world-music', 'Folk & World Music', 'arts-culture', 'Folk, world, traditional and roots music'),
  ('comedy', 'Comedy', 'arts-culture', 'Humor, stand-up, funny content'),
  ('horror', 'Horror', 'arts-culture', 'Horror fiction, scary stories, terror'),
  ('science-fiction', 'Science Fiction', 'arts-culture', 'Sci-fi, speculative fiction, futurism'),
  ('fantasy', 'Fantasy', 'arts-culture', 'Fantasy fiction, magical worlds, mythology-inspired'),
  ('thriller', 'Thriller', 'arts-culture', 'Suspense, crime thrillers, page-turners'),
  ('mystery', 'Mystery', 'arts-culture', 'Detective fiction, whodunits, puzzles'),
  ('romance', 'Romance', 'arts-culture', 'Romance fiction, love stories, relationships'),
  ('drama', 'Drama', 'arts-culture', 'Dramatic fiction, character-driven stories'),
  ('historical-fiction', 'Historical Fiction', 'arts-culture', 'Fiction set in historical periods'),
  ('literary-fiction', 'Literary Fiction', 'arts-culture', 'Literary fiction, character study, prose craft'),
  ('documentary', 'Documentary', 'arts-culture', 'Non-fiction films, docuseries, factual'),
  ('memoir', 'Memoir', 'arts-culture', 'Personal narratives, life stories, autobiography'),
  ('satire', 'Satire', 'arts-culture', 'Satirical content, parody, social commentary'),
  ('journalism', 'Journalism', 'arts-culture', 'Reporting, investigative journalism, news media'),
  ('ancient-history', 'Ancient History', 'history-ideas', 'Ancient civilizations, antiquity, archaeology'),
  ('medieval-history', 'Medieval History', 'history-ideas', 'Middle Ages, feudalism, medieval life'),
  ('modern-history', 'Modern History', 'history-ideas', 'Recent history, 20th century, contemporary events'),
  ('military-history', 'Military History', 'history-ideas', 'Wars, battles, military strategy, weapons'),
  ('philosophy', 'Philosophy', 'history-ideas', 'Philosophical ideas, thinkers, ethics'),
  ('ethics', 'Ethics', 'history-ideas', 'Moral philosophy, ethical dilemmas, values'),
  ('political-science', 'Political Science', 'history-ideas', 'Politics, government, political theory'),
  ('geopolitics', 'Geopolitics', 'history-ideas', 'International relations, global power dynamics'),
  ('economics', 'Economics', 'history-ideas', 'Economic theory, markets, finance'),
  ('law', 'Law', 'history-ideas', 'Legal systems, court cases, legislation'),
  ('religion', 'Religion', 'history-ideas', 'Religious beliefs, traditions, theology'),
  ('mythology', 'Mythology', 'history-ideas', 'Myths, legends, folklore, gods'),
  ('anthropology', 'Anthropology', 'history-ideas', 'Human cultures, societies, evolution'),
  ('archaeology', 'Archaeology', 'history-ideas', 'Excavations, artifacts, ancient discoveries'),
  ('sociology', 'Sociology', 'history-ideas', 'Society, social structures, human behavior'),
  ('linguistics', 'Linguistics', 'history-ideas', 'Language structure, evolution, phonetics'),
  ('activism', 'Activism', 'history-ideas', 'Social movements, protests, advocacy'),
  ('disability', 'Disability', 'history-ideas', 'Disability rights, accessibility, inclusion'),
  ('aging', 'Aging', 'history-ideas', 'Gerontology, longevity, aging society'),
  ('gender', 'Gender', 'history-ideas', 'Gender studies, identity, equality'),
  ('race-ethnicity', 'Race & Ethnicity', 'history-ideas', 'Race relations, ethnic studies, diversity'),
  ('immigration', 'Immigration', 'history-ideas', 'Migration, borders, refugee issues'),
  ('disaster', 'Disaster', 'history-ideas', 'Natural disasters, catastrophes, emergency response'),
  ('criminal-justice', 'Criminal Justice', 'history-ideas', 'Criminal justice, law enforcement, criminology'),
  ('drug-policy', 'Drug Policy', 'history-ideas', 'Drug laws, harm reduction, addiction policy'),
  ('energy', 'Energy', 'history-ideas', 'Energy policy, renewables, fossil fuels'),
  ('agriculture', 'Agriculture', 'history-ideas', 'Farming, food production, agricultural science'),
  ('transportation', 'Transportation', 'history-ideas', 'Transit, infrastructure, vehicles, mobility'),
  ('manufacturing', 'Manufacturing', 'history-ideas', 'Industrial production, factories, supply chain'),
  ('video-games', 'Video Games', 'games-hobbies', 'Gaming, game industry, game reviews'),
  ('game-design', 'Game Design', 'games-hobbies', 'Game mechanics, level design, game development'),
  ('board-games', 'Board Games', 'games-hobbies', 'Tabletop games, card games, strategy games'),
  ('tabletop-rpgs', 'Tabletop RPGs', 'games-hobbies', 'D&D, role-playing games, TTRPGs'),
  ('chess', 'Chess', 'games-hobbies', 'Chess strategy, tournaments, puzzles'),
  ('puzzles', 'Puzzles', 'games-hobbies', 'Crosswords, logic puzzles, brain teasers'),
  ('sports', 'Sports', 'games-hobbies', 'Athletics, professional sports, competitions'),
  ('mma', 'MMA', 'games-hobbies', 'Mixed martial arts, UFC, combat sports'),
  ('outdoor-adventure', 'Outdoor Adventure', 'games-hobbies', 'Hiking, camping, climbing, exploration'),
  ('fishing', 'Fishing', 'games-hobbies', 'Angling, fly fishing, sport fishing'),
  ('hunting', 'Hunting', 'games-hobbies', 'Hunting techniques, wildlife management'),
  ('cooking', 'Cooking', 'games-hobbies', 'Recipes, culinary techniques, food preparation'),
  ('baking', 'Baking', 'games-hobbies', 'Bread, pastries, desserts, baking techniques'),
  ('food-culture', 'Food Culture', 'games-hobbies', 'Cuisine, food history, dining culture'),
  ('craft-beer', 'Craft Beer', 'games-hobbies', 'Brewing, beer tasting, microbreweries'),
  ('whiskey', 'Whiskey', 'games-hobbies', 'Whisky, bourbon, scotch, distillation'),
  ('coffee', 'Coffee', 'games-hobbies', 'Coffee culture, brewing methods, beans'),
  ('wine', 'Wine', 'games-hobbies', 'Wine tasting, viticulture, wine regions'),
  ('tea', 'Tea', 'games-hobbies', 'Tea culture, tea varieties, brewing, ceremony'),
  ('gardening', 'Gardening', 'games-hobbies', 'Plants, horticulture, landscaping'),
  ('diy', 'DIY', 'games-hobbies', 'Do-it-yourself projects, home improvement'),
  ('home-improvement', 'Home Improvement', 'games-hobbies', 'Home renovation, repair, interior projects'),
  ('woodworking', 'Woodworking', 'games-hobbies', 'Woodcraft, carpentry, furniture making'),
  ('crafts', 'Crafts', 'games-hobbies', 'Handicrafts, knitting, sewing, making'),
  ('collecting', 'Collecting', 'games-hobbies', 'Collectibles, antiques, memorabilia'),
  ('automotive', 'Automotive', 'games-hobbies', 'Cars, motorcycles, vehicles, auto culture'),
  ('pets', 'Pets', 'games-hobbies', 'Dogs, cats, pet care, animal companions'),
  ('birding', 'Birding', 'games-hobbies', 'Birdwatching, ornithology hobby, species identification'),
  ('cycling', 'Cycling', 'games-hobbies', 'Road cycling, mountain biking, bike commuting'),
  ('oddities', 'Oddities', 'weird-wonderful', 'Strange facts, curiosities, unusual phenomena'),
  ('true-crime', 'True Crime', 'weird-wonderful', 'Real crime stories, investigations, mysteries'),
  ('unsolved-mysteries', 'Unsolved Mysteries', 'weird-wonderful', 'Cold cases, unexplained events, enigmas'),
  ('paranormal', 'Paranormal', 'weird-wonderful', 'Ghosts, UFOs, supernatural phenomena'),
  ('conspiracy-theories', 'Conspiracy Theories', 'weird-wonderful', 'Conspiracies, cover-ups, alternative narratives'),
  ('urban-legends', 'Urban Legends', 'weird-wonderful', 'Modern folklore, creepypasta, myths'),
  ('lost-media', 'Lost Media', 'weird-wonderful', 'Lost films, missing recordings, media archaeology'),
  ('internet-mysteries', 'Internet Mysteries', 'weird-wonderful', 'Online enigmas, cicada 3301, web puzzles'),
  ('cryptozoology', 'Cryptozoology', 'weird-wonderful', 'Bigfoot, Loch Ness, hidden creatures'),
  ('absurdist-humor', 'Absurdist Humor', 'weird-wonderful', 'Surreal comedy, weird humor, dada'),
  ('hoaxes', 'Hoaxes', 'weird-wonderful', 'Hoaxes, deception, debunking, fake news'),
  ('travel', 'Travel', 'people-places', 'Destinations, travel tips, tourism'),
  ('cities', 'Cities', 'people-places', 'Urban life, city planning, metropolitan culture'),
  ('maps', 'Maps', 'people-places', 'Cartography, mapping, geography'),
  ('geography', 'Geography', 'people-places', 'Physical and human geography, places, regions'),
  ('biography', 'Biography', 'people-places', 'Life stories, historical figures, memoirs'),
  ('indigenous-cultures', 'Indigenous Cultures', 'people-places', 'Native peoples, traditional knowledge, heritage'),
  ('subcultures', 'Subcultures', 'people-places', 'Countercultures, niche communities, scenes'),
  ('festivals', 'Festivals', 'people-places', 'Cultural festivals, celebrations, events'),
  ('migration', 'Migration', 'people-places', 'Human migration, diaspora, movement'),
  ('languages', 'Languages', 'people-places', 'World languages, language learning, polyglots'),
  ('psychology', 'Psychology', 'mind-body', 'Human mind, behavior, mental processes'),
  ('mental-health', 'Mental Health', 'mind-body', 'Wellness, therapy, mental illness, self-care'),
  ('mindfulness', 'Mindfulness', 'mind-body', 'Meditation, presence, contemplative practice'),
  ('sleep', 'Sleep', 'mind-body', 'Sleep science, dreams, sleep health'),
  ('fitness', 'Fitness', 'mind-body', 'Exercise, workouts, physical training'),
  ('yoga', 'Yoga', 'mind-body', 'Yoga practice, philosophy, asanas'),
  ('nutrition', 'Nutrition', 'mind-body', 'Diet, food science, healthy eating'),
  ('wellness', 'Wellness', 'mind-body', 'Holistic health, well-being, self-improvement'),
  ('relationships', 'Relationships', 'mind-body', 'Dating, marriage, interpersonal dynamics'),
  ('parenting', 'Parenting', 'mind-body', 'Child-rearing, family life, education'),
  ('education', 'Education', 'mind-body', 'Learning, teaching, pedagogy, schools'),
  ('career', 'Career', 'mind-body', 'Jobs, career development, workplace, professional growth'),
  ('productivity', 'Productivity', 'mind-body', 'Time management, efficiency, workflows'),
  ('personal-development', 'Personal Development', 'mind-body', 'Self-improvement, growth, life skills'),
  ('personal-finance', 'Personal Finance', 'mind-body', 'Budgeting, saving, investing, money management'),
  ('beauty', 'Beauty', 'mind-body', 'Skincare, cosmetics, beauty routines, grooming'),
  ('biohacking', 'Biohacking', 'mind-body', 'Human optimization, nootropics, quantified self');
